version: "3.8"
services:
  # slowfast:
  #   build:
  #     context: .
  #     dockerfile: slowfast.Dockerfile  
  #   image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/slowfast
  #   volumes:
  #     - /mnt/wato-drive/road:/road
  #     #- ./SlowFast:/project/SlowFast
  #   ipc: host
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

  raft:
    build:
      context: .
      dockerfile: raft.Dockerfile
    #image: ufoym/deepo:pytorch-py38-cu113
    volumes:
      - /mnt/wato-drive/road:/road
      - ./:/RAFT
    ipc: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]


